### PR TITLE
Feat/add token to reader sa

### PR DESCRIPTION
**Pull request by tkircsi**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no
| License         | Apache 2.0

### What's in this PR?
This PR adds the feature to cluster-registry to work with Kubernetes 1.24 >= and OpenShift 4.11.

### Why?
service-account-token  Secret handling has changed in Kubernetes 1.24 and above and works differently in OpenShift 4.11. cluster-registry can't create the cluster secret without this change.

### Additional context
Kubernetes 1.24 and above and OpenShift 4.11 handles service-account-token secrets differently than the previous versions. This change makes cluster-registry to able to work with these distributions and versions.

### Checklist
- [x] Implementation tested
- [x] User guide and development docs updated (if needed)

### CODE REVIEW

**Review by tiswanso — COMMENTED** [review]
should the kubebuilder tools version stuff be in this PR?  can that be submitted separately?

**Comment by tkircsi** [comment]
@tiswanso You'r right. It's more suitable in a separate PR with other version bumps. I restored the previous version.

**Review by nishantapatil3 — APPROVED** [review]
lgtm! Thanks

**Review by kristofgyuracz — COMMENTED** [review]
lgtm.

**Pull request merged**
